parameters:
  InventoryReportName: ''
  ManagementCostReportName: ''
 
jobs:
- job: PublishConfluenceReports
  displayName: Publish Confluence Reports
  workspace:
      clean: all
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'current' # Options: current, specific
      artifact: 'Scripts'
      path: '$(Pipeline.Workspace)'
  - task: PowerShell@2
    displayName: 'Installing ConfluencePS'
    inputs:
      targetType: inline
      script: 'Install-Module ConfluencePS -force'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      errorActionPreference: 'stop'
  - task: PowerShell@2
    displayName: 'Importing ConfluencePS'
    inputs:
      targetType: inline
      script: 'Import-Module ConfluencePS -force'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      errorActionPreference: 'stop'
  - task: AzurePowerShell@5
    displayName: 'Publish Confluence Inventory Report'
    inputs:
      azureSubscription: 'Visual Studio Enterprise (cb5ab4a7-dd08-4be3-9d7e-9f68ae30f224)'
      ScriptPath: '$(Pipeline.Workspace)/PublishResourceReport.ps1'
      ScriptArguments: '-BaseURI $(BaseURI)
                        -confluenceApiUsername $(ConfluenceApiUsername) 
                        -ConfluenceApiTokenPass $(ConfluenceApiTokenPass)  
                        -ConfluenceInventoryPageId $(ConfluenceInventoryPageId)
                        -ReportName "${{ parameters.InventoryReportName }}"'
      FailOnStandardError: true
      azurePowerShellVersion: LatestVersion
  - task: AzurePowerShell@5
    displayName: 'Publish Confluence ManagementCost Report'
    inputs:
      azureSubscription: 'Visual Studio Enterprise (cb5ab4a7-dd08-4be3-9d7e-9f68ae30f224)'
      ScriptPath: '$(Pipeline.Workspace)/PublishManagementReport.ps1'
      ScriptArguments: '-BaseURI $(BaseURI)
                        -confluenceApiUsername $(ConfluenceApiUsername) 
                        -ConfluenceApiTokenPass $(ConfluenceApiTokenPass)  
                        -ConfluenceManagementCostPageId $(ConfluenceManagementCostPageId)
                        -ReportName "${{ parameters.ManagementCostReportName }}"'
      FailOnStandardError: true
      azurePowerShellVersion: LatestVersion
