parameters:
  InventoryReportName: ''
  ManagementCostReportName: ''
 
jobs:
- job: PublishConfluenceInventoryReport
  displayName: Publish Confluence Inventory Report
  workspace:
      clean: all
  steps:
  - task: PowerShell@2
    displayName: 'Installing ConfluencePS'
    inputs:
      targetType: inline
      script: 'Install-Module ConfluencePS -force'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      errorActionPreference: 'stop'
  - task: PowerShell@2
    displayName: 'Importing ConfluencePS'
    inputs:
      targetType: inline
      script: 'Import-Module ConfluencePS -force'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      errorActionPreference: 'stop'
  - task: AzurePowerShell@5
    displayName: 'Publish Confluence Inventory Report'
    inputs:
      azureSubscription: 'Visual Studio Enterprise (cb5ab4a7-dd08-4be3-9d7e-9f68ae30f224)'
      ScriptPath: '$(System.DefaultWorkingDirectory)/PowerShellScripts/PublishResourceReport.ps1'
      ScriptArguments: '-BaseURI $(BaseURI)
                        -confluenceApiUsername $(ConfluenceApiUsername) 
                        -ConfluenceApiTokenPass $(ConfluenceApiTokenPass)  
                        -ConfluencePageId $(ConfluenceInventoryPageId)
                        -ReportName "${{ parameters.InventoryReportName }}"'
      FailOnStandardError: true
      azurePowerShellVersion: LatestVersion
  - task: AzurePowerShell@5
    displayName: 'Publish Confluence ManagementCost Report'
    inputs:
      azureSubscription: 'Visual Studio Enterprise (cb5ab4a7-dd08-4be3-9d7e-9f68ae30f224)'
      ScriptPath: '$(System.DefaultWorkingDirectory)/PowerShellScripts/PublishManagementReport.ps1'
      ScriptArguments: '-BaseURI $(BaseURI)
                        -confluenceApiUsername $(ConfluenceApiUsername) 
                        -ConfluenceApiTokenPass $(ConfluenceApiTokenPass)  
                        -ConfluencePageId $(ConfluenceManagementCostPageId)
                        -ReportName "${{ parameters.ManagementCostReportName }}"'
      FailOnStandardError: true
      azurePowerShellVersion: LatestVersion
