parameters:
  BaseURI: ''
  ConfluenceApiUsername:  ''
  ConfluenceApiTokenPass:  ''
  ConfluenceInventoryPageId:  ''
 
jobs:
- job: PublishConfluenceInventoryReport
  displayName: Publish Confluence Inventory Report
  workspace:
      clean: all
  steps:
  - task: AzurePowerShell@5
    displayName: 'Publish Confluence Inventory Report'
    inputs:
      azureSubscription: 'Visual Studio Enterprise (cb5ab4a7-dd08-4be3-9d7e-9f68ae30f224)'
      ScriptPath: '$(System.DefaultWorkingDirectory)/PowerShellScripts/Create-AppAuthentication-stupid.ps1'
      ScriptArguments: '-BaseURI $(BaseURI)
                        -confluenceApiUsername $(ConfluenceApiUsername) 
                        -ConfluenceApiTokenPass $(ConfluenceApiTokenPass)  
                        -ConfluenceInventoryPageId $(ConfluenceInventoryPageId)'
      FailOnStandardError: true
      azurePowerShellVersion: LatestVersion
